---
- name: Update apt
  apt: update_cache=yes
  sudo: yes
- name: Install base packages
  apt: pkg={{item}} state=latest
  sudo: yes
  with_items:
    - git
    - build-essential
    - nodejs
    - curl
    - postgresql
    - postgresql-client
    - libpq-dev
    - postgresql-contrib
    - kodi
    - atom
    - dropbox
    - skype
    - hipchat

https://www.dropbox.com/download?dl=packages/dropbox.py
cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
