---
- name: Update apt
  apt: update_cache=yes
  sudo: yes
- name: Install base packages
  apt: pkg={{item}} state=latest
  sudo: yes
  with_items:
    - git
    - build-essential
    - nodejs
    - curl
    - postgresql
    - postgresql-client
    - libpq-dev
    - postgresql-contrib
    - kodi
    - atom
    - dropbox
    - skype
    - hipchat
    - openvpn
    - vpnc
    - vibrancy-colors
    - unity-tweak-tool
    - libcurl3-dev
    - curl
    - libpq
- name: Install atom packages
  shell: apm install {{item}}
  sudo: no
  with_items:
    - atom-beautify
    - atom-sync
    - language-ansible
    - file-icons
- name: Install rvm
  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3; curl -sSL https://get.rvm.io | bash -s stable
- name: Install ruby 2.2.1
  shell: rvm install 2.2.1
- name: Install rvm for cron
  shell: rvm cron setup;gem install bundler
